version: '2'
services:
  reporting-service-prod:
    container_name: reporting-service-prod
    image: elijahahianyo/trade-project:reporting-service-prod
    ports:
      - 36000:36000
    networks:
      - trade_project

networks:
  trade_project:
    external: true